package com.calvin.android.module.compiler;

/**
 * Author:linhu
 * Email:lhzheng@grandstream.cn
 * Date:19-7-4
 */
public class ModuleUtils {

    public static final String FACADE_PACKAGENAME = "com.calvin.android.modulebus";

    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MODULEBUS.";

    public static final String BS_API = FACADE_PACKAGENAME  + ".BsIApi";
}
